apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: logging
type: Opaque
stringData:
  username: elastic
  password: RJxQnPCh3L..... #Create password inside elasticsearch pod:
# cd bin
# ./elasticsearch-setup-password and follow instructions
