---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: logging
type: Opaque
stringData:
  username: elastic
  password: changeme
      # Create password inside elasticsearch pod:
      # cd bin
      # ./elasticsearch-setup-password and follow instructions
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-auth
  namespace: logging
type: Opaque
stringData:
  password: changeme  #Add your elasticpassword

---

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: logging
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.17.5
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: single-node
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: password
            - name: xpack.security.enabled
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: data
          emptyDir: {}
