apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type cri
        time_key time
      </parse>
    </source>

    <filter kubernetes.**>
      @type grep
      <regexp>
        key $.kubernetes.namespace_name
        pattern ^default$
      </regexp>
    </filter>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <filter kubernetes.**>
      @type parser
      key_name log
      reserve_data true
      remove_key_name_field true
      <parse>
        @type json
      </parse>
    </filter>

    <match kubernetes.**>
      @type elasticsearch
      host elasticsearch.logging.svc.cluster.local
      port 9200
      scheme http
      user elastic
      password "#{ENV['ELASTICSEARCH_PASSWORD']}"
      logstash_format true  
      logstash_prefix kubernetes
      logstash_dateformat %Y.%m.%d
      include_tag_key true
      flush_interval 5s
      reconnect_on_error true
      reload_on_failure true
      request_timeout 10s
    </match>
