---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
  labels:
    app: fluentd
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kube.*
      format json
      read_from_head true
    </source>

    <filter kube.**>
      @type kubernetes_metadata
    </filter>

    <match **>
      @type elasticsearch
      @id out_es
      host elasticsearch.logging.svc
      port 9200
      scheme http
      ssl_verify false
      user elastic
      password "#{ENV['ES_PASSWORD']}"
      logstash_format true
      logstash_prefix fluentd
      include_tag_key true
      reconnect_on_error true
      reload_connections true
      request_timeout 30s
    </match>
