apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin  # You can replace this with a more restrictive role
subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: logging
