<source>
  @type tail
  path /var/log/containers/*.log
  pos_file /var/log/fluentd-containers.log.pos
  tag kube.*
  format multiline
  format_firstline /^\d{4}-\d{2}-\d{2}/
  format1 /^(?<time>\S+)\s+(?<level>\w+)\s+(?<message>.+)$/
  time_key time
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  read_from_head true
</source>

<filter kube.**>
  @type parser                     
  key_name log
  format json                      
  reserve_data true
</filter>

<filter kube.**>
  @type kubernetes_metadata
</filter>

<match kube.**>
  @type elasticsearch
  host elasticsearch.logging.svc.cluster.local
  port 9200
  scheme http
  user elastic
  password OLVsB9w6cqLuvhOZIp5k
  logstash_format true
  logstash_prefix fluentd
  include_tag_key true
  tag_key @log_name
  flush_interval 5s
  <buffer>
    @type file
    path /var/log/fluentd-buffers/es
    flush_mode interval
    flush_interval 5s
    retry_forever
  </buffer>
</match>
