apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
spec:
  selector:
    app: kibana
  type: ClusterIP  # Change to NodePort if needed
  ports:
    - port: 5601
      targetPort: 5601
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.17.5
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
            - name: ELASTICSEARCH_USERNAME
              value: "kibana_system"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kibana-auth
                  key: kibana_password
            - name: XPACK_SECURITY_ENABLED
              value: "true"

              ## For version 9.0.0 and newer! usernname & password not acceptable
#            - name: KIBANA_ENCRYPTED_SAVED_OBJECTS_ENCRYPTIONKEY
#             value: "Th1sIsA32CharSecretEncryptionKey!!"
