apiVersion: v1
kind: Secret
metadata:
  name: kibana-auth
  namespace: logging
type: Opaque
stringData:
  kibana_password: 8LXE9WZf9C4KW2TZ8R2G ## Paste password from kibana_system from elastic-generator
