apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
#==============================================================================
####### NODE PORT ###### 
#apiVersion: v1
#kind: Service
#metadata:
#  name: kibana
#  namespace: logging
#spec:
#  selector:
#    app: kibana
#  type: NodePort
#  ports:
#    - name: http
#      port: 5601
#      targetPort: 5601
#      nodePort: 30601  # Välj en port inom tillåtna intervallet 30000–32767
####### NODE PORT ###### 
#==============================================================================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:9.0.0
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
            - name: ELASTICSEARCH_SERVICEACCOUNTTOKEN # Äldre version av ES och KIBANA krävs TOKEN!   ### Går ej köra username/password
              valueFrom:
                secretKeyRef:
                  name: kibana-service-token
                  key: token ## Använder token från kibana-secret-token skapad inne i es-pod
            - name: XPACK_SECURITY_ENABLED
              value: "true"
